# 🧠 PyTorch 张量基础教程

## 📚 本节学习目标
- 理解张量(Tensor)的基本概念
- 掌握张量的创建方法
- 学会张量的基本操作和属性
- 熟悉张量的形状变换
- 掌握张量的数学运算
- 了解张量与NumPy的关系

---

In [ ]:
# 导入必要的库
import torch
import numpy as np
import sys
import os

# 添加项目根目录到路径,定位项目中的文件或目录，方便跨模块引用。
project_root = os.path.abspath(os.path.join(os.getcwd(), '../..'))
sys.path.insert(0, project_root)

from utils.common import get_device, print_tensor_info

print(f"🔥 PyTorch 版本: {torch.__version__}")
device = get_device()

🔥 PyTorch 版本: 2.7.1+cu126
🚀 使用 CUDA: NVIDIA GeForce GTX 1050 Ti
📊 CUDA 内存: 4.2 GB


## 🎯 1. 什么是张量？

**张量(Tensor)** 是PyTorch中最基本的数据结构，可以理解为：

- **0维张量**: 标量 (scalar) - 一个数字
- **1维张量**: 向量 (vector) - 一行数字
- **2维张量**: 矩阵 (matrix) - 表格形式的数据
- **3维张量**: 立方体 - 比如RGB图像 (高×宽×通道)
- **4维张量**: 一批图像 (批次×通道×高×宽)
- **更高维**: 复杂的多维数据

### 🎭 生活中的类比
- **标量**: 温度 (23.5°C)
- **向量**: 一天的温度记录 [20, 22, 25, 28, 26]
- **矩阵**: 一周的温度记录表
- **3维张量**: 一个月每天每小时的温度记录

---

## 🏗️ 2. 张量的创建方法

让我们学习各种创建张量的方法：

### 2.1 从数据直接创建

In [2]:
# 📊 从Python列表创建张量
print("🔢 从列表创建张量：")

# 0维张量 (标量)
scalar = torch.tensor(42)
print_tensor_info(scalar, "标量")
print()

# 1维张量 (向量)
vector = torch.tensor([1, 2, 3, 4, 5])
print_tensor_info(vector, "向量")
print()

# 2维张量 (矩阵)
matrix = torch.tensor([[1, 2, 3], 
                      [4, 5, 6]])
print_tensor_info(matrix, "矩阵")
print()

# 3维张量
tensor_3d = torch.tensor([[[1, 2], [3, 4]], 
                         [[5, 6], [7, 8]]])
print_tensor_info(tensor_3d, "3维张量")

🔢 从列表创建张量：
📊 标量 信息:
  形状: torch.Size([])
  数据类型: torch.int64
  设备: cpu
  内存占用: 0.00 MB
  值: 42

📊 向量 信息:
  形状: torch.Size([5])
  数据类型: torch.int64
  设备: cpu
  内存占用: 0.00 MB
  值: tensor([1, 2, 3, 4, 5])

📊 矩阵 信息:
  形状: torch.Size([2, 3])
  数据类型: torch.int64
  设备: cpu
  内存占用: 0.00 MB
  值: tensor([[1, 2, 3],
        [4, 5, 6]])

📊 3维张量 信息:
  形状: torch.Size([2, 2, 2])
  数据类型: torch.int64
  设备: cpu
  内存占用: 0.00 MB
  值: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


### 2.2 特殊值张量的创建

In [3]:
print("🎨 创建特殊值张量：")

# 全零张量
zeros = torch.zeros(3, 4)
print(f"全零张量 (3x4):\n{zeros}\n")

# 全一张量
ones = torch.ones(2, 3)
print(f"全一张量 (2x3):\n{ones}\n")

# 对角线为1的单位矩阵
eye = torch.eye(3)
print(f"单位矩阵 (3x3):\n{eye}\n")

# 填充特定值
filled = torch.full((2, 3), 7.5)
print(f"填充7.5的张量 (2x3):\n{filled}")

🎨 创建特殊值张量：
全零张量 (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

全一张量 (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

单位矩阵 (3x3):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

填充7.5的张量 (2x3):
tensor([[7.5000, 7.5000, 7.5000],
        [7.5000, 7.5000, 7.5000]])


### 2.3 随机张量的创建

In [4]:
print("🎲 创建随机张量：")

# 设置随机种子以便结果可重现
torch.manual_seed(42)

# 0-1之间的均匀分布随机数
random_uniform = torch.rand(2, 3)
print(f"均匀分布随机张量 [0,1):\n{random_uniform}\n")

# 标准正态分布随机数 (均值0，标准差1)
random_normal = torch.randn(2, 3)
print(f"正态分布随机张量 N(0,1):\n{random_normal}\n")

# 指定范围的随机整数
random_int = torch.randint(0, 10, (2, 3))
print(f"随机整数张量 [0,10):\n{random_int}\n")

# 类似于另一个张量的随机张量
like_tensor = torch.randn_like(matrix.float())
print(f"与matrix相同形状的随机张量:\n{like_tensor}")

🎲 创建随机张量：
均匀分布随机张量 [0,1):
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

正态分布随机张量 N(0,1):
tensor([[ 1.1561,  0.3965, -2.4661],
        [ 0.3623,  0.3765, -0.1808]])

随机整数张量 [0,10):
tensor([[7, 6, 9],
        [6, 3, 1]])

与matrix相同形状的随机张量:
tensor([[ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])


### 2.4 数值序列张量

In [8]:
print("📈 创建数值序列张量：")

# 等差数列
arange_tensor = torch.arange(0, 10, 2)  # 从0到10，步长为2
print(f"等差数列 arange(0, 10, 2): {arange_tensor}\n")

# 线性等分
linspace_tensor = torch.linspace(0, 1, 5)  # 从0到1，等分成5个点
print(f"线性等分 linspace(0, 1, 5): {linspace_tensor}\n")

# 对数等分
logspace_tensor = torch.logspace(0, 2, 5)  # 10^0 到 10^2，等分成5个点
print(f"对数等分 logspace(0, 2, 5): {logspace_tensor}")

📈 创建数值序列张量：
等差数列 arange(0, 10, 2): tensor([0, 2, 4, 6, 8])

线性等分 linspace(0, 1, 5): tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

对数等分 logspace(0, 2, 5): tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])


---

## 🔍 3. 张量的属性

每个张量都有几个重要的属性：

- **shape/size**: 张量的形状
- **dtype**: 数据类型
- **device**: 存储设备(CPU/GPU)
- **requires_grad**: 是否需要计算梯度

In [9]:
# 创建一个示例张量
example_tensor = torch.randn(3, 4, 5, dtype=torch.float32, device=device)

print("🔍 张量属性详解：")
print(example_tensor)

print(f"📐 形状 (shape): {example_tensor.shape}")
print(f"📐 大小 (size): {example_tensor.size()}")
print(f"🔢 维度数 (ndim): {example_tensor.ndim}")
print(f"📊 元素总数 (numel): {example_tensor.numel()}")
print(f"🎭 数据类型 (dtype): {example_tensor.dtype}")
print(f"💻 设备 (device): {example_tensor.device}")
print(f"🧮 需要梯度 (requires_grad): {example_tensor.requires_grad}")
print(f"💾 内存布局 (layout): {example_tensor.layout}")
print(f"📏 步长 (stride): {example_tensor.stride()}")

🔍 张量属性详解：
tensor([[[ 0.1391, -0.1082, -0.7174,  0.7566,  0.3715],
         [-1.0049,  0.0083,  0.3277,  0.2829, -0.8926],
         [-0.1626, -0.8062, -0.1168, -1.6124, -0.1541],
         [-0.0646, -0.5324,  0.0533, -0.0314, -0.7431]],

        [[-1.1582, -0.0249, -0.7584, -0.4157,  0.6389],
         [-0.2545, -1.2304, -1.5822,  0.6431,  0.9715],
         [-1.3249, -1.0006, -0.4556,  0.4031, -0.7707],
         [-1.1757, -0.1555, -0.6527,  0.2520,  0.4590]],

        [[ 1.8932,  0.1633, -0.2634, -1.1079,  0.7673],
         [-1.1230,  0.3047,  0.3896, -0.2520, -1.0066],
         [ 0.2927, -1.1003,  1.9016, -1.5185,  1.6850],
         [-1.3713,  0.2893,  0.3939,  0.6529, -0.5519]]], device='cuda:0')
📐 形状 (shape): torch.Size([3, 4, 5])
📐 大小 (size): torch.Size([3, 4, 5])
🔢 维度数 (ndim): 3
📊 元素总数 (numel): 60
🎭 数据类型 (dtype): torch.float32
💻 设备 (device): cuda:0
🧮 需要梯度 (requires_grad): False
💾 内存布局 (layout): torch.strided
📏 步长 (stride): (20, 5, 1)


### 3.1 数据类型详解

PyTorch支持多种数据类型，选择合适的数据类型很重要：

In [10]:
print("🎭 常用数据类型：")

# 整数类型
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
print(f"int32: {int_tensor}, dtype: {int_tensor.dtype}")

# 长整数类型 (默认整数类型)
long_tensor = torch.tensor([1, 2, 3], dtype=torch.long)
print(f"long: {long_tensor}, dtype: {long_tensor.dtype}")

# 单精度浮点数 (默认浮点类型)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print(f"float32: {float_tensor}, dtype: {float_tensor.dtype}")

# 双精度浮点数
double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.double)
print(f"double: {double_tensor}, dtype: {double_tensor.dtype}")

# 布尔类型
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)
print(f"bool: {bool_tensor}, dtype: {bool_tensor.dtype}")

print("\n💡 类型转换：")
# 类型转换
converted = int_tensor.float()  # 转换为float32
print(f"int32 → float32: {converted}, dtype: {converted.dtype}")

🎭 常用数据类型：
int32: tensor([1, 2, 3], dtype=torch.int32), dtype: torch.int32
long: tensor([1, 2, 3]), dtype: torch.int64
float32: tensor([1., 2., 3.]), dtype: torch.float32
double: tensor([1., 2., 3.], dtype=torch.float64), dtype: torch.float64
bool: tensor([ True, False,  True]), dtype: torch.bool

💡 类型转换：
int32 → float32: tensor([1., 2., 3.]), dtype: torch.float32


---

## 🔄 4. 张量的形状操作

**形状操作是深度学习中最常用的操作之一，让我们详细学习：**

In [11]:
# 创建一个示例张量
x = torch.arange(24).reshape(2, 3, 4)
print(f"🎯 原始张量 x:\n{x}")
print(f"形状: {x.shape}\n")

print("🔄 形状变换操作：")

# 1. reshape: 改变形状但保持元素总数不变
reshaped = x.reshape(4, 6)
print(f"reshape(4, 6):\n{reshaped}")
print(f"形状: {reshaped.shape}\n")

# 2. view: 类似reshape但要求内存连续
viewed = x.view(3, 8)
print(f"view(3, 8):\n{viewed}")
print(f"形状: {viewed.shape}\n")

# 3. flatten: 展平为1维
flattened = x.flatten()
print(f"flatten(): {flattened}")
print(f"形状: {flattened.shape}\n")

# 4. squeeze: 移除大小为1的维度
squeezed_tensor = torch.randn(1, 3, 1, 4)
squeezed = squeezed_tensor.squeeze()
print(f"squeeze前形状: {squeezed_tensor.shape}")
print(f"squeeze后形状: {squeezed.shape}\n")

# 5. unsqueeze: 添加大小为1的维度
unsqueezed = x.unsqueeze(0)  # 在位置0添加维度
print(f"unsqueeze(0)前形状: {x.shape}")
print(f"unsqueeze(0)后形状: {unsqueezed.shape}")

🎯 原始张量 x:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
形状: torch.Size([2, 3, 4])

🔄 形状变换操作：
reshape(4, 6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
形状: torch.Size([4, 6])

view(3, 8):
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
形状: torch.Size([3, 8])

flatten(): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
形状: torch.Size([24])

squeeze前形状: torch.Size([1, 3, 1, 4])
squeeze后形状: torch.Size([3, 4])

unsqueeze(0)前形状: torch.Size([2, 3, 4])
unsqueeze(0)后形状: torch.Size([1, 2, 3, 4])


### 4.1 维度置换和转置

In [ ]:
print("🔄 维度置换操作：")

# 创建一个3维张量 (批次, 高度, 宽度)
image_like = torch.randn(2, 28, 28)
print(f"原始形状 (batch, height, width): {image_like.shape}")

# transpose: 交换两个维度
transposed = image_like.transpose(1, 2)  # 交换维度1和2
print(f"transpose(1, 2)后形状: {transposed.shape}")

# permute: 重新排列所有维度
permuted = image_like.permute(2, 0, 1)  # 重排为 (width, batch, height)
print(f"permute(2, 0, 1)后形状: {permuted.shape}")

# 对于2D矩阵，可以用.T进行转置
matrix_2d = torch.randn(3, 4)
print(f"\n2D矩阵转置：")
print(f"原始形状: {matrix_2d.shape}")
print(f"转置后形状: {matrix_2d.T.shape}")

---

## 🧮 5. 张量的数学运算

PyTorch提供了丰富的数学运算，支持元素级运算和矩阵运算：

In [ ]:
print("🧮 基本数学运算：")

# 创建两个示例张量
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"张量 a:\n{a}")
print(f"张量 b:\n{b}\n")

# 元素级运算
print("🔢 元素级运算：")
print(f"加法 a + b:\n{a + b}\n")
print(f"减法 a - b:\n{a - b}\n")
print(f"乘法 a * b (元素级):\n{a * b}\n")
print(f"除法 a / b:\n{a / b}\n")
print(f"幂运算 a ** 2:\n{a ** 2}\n")

# 矩阵运算
print("📊 矩阵运算：")
print(f"矩阵乘法 a @ b:\n{a @ b}\n")
print(f"矩阵乘法 torch.mm(a, b):\n{torch.mm(a, b)}\n")

# 广播机制
print("📡 广播机制：")
scalar = 10
print(f"张量与标量运算 a + {scalar}:\n{a + scalar}\n")

vector = torch.tensor([1, 2])
print(f"张量与向量运算 a + {vector}:\n{a + vector}")

### 5.1 聚合运算

In [ ]:
print("📊 聚合运算：")

# 创建一个示例张量
data = torch.randn(3, 4)
print(f"示例数据:\n{data}\n")

# 统计运算
print(f"求和 sum(): {data.sum()}")
print(f"平均值 mean(): {data.mean():.4f}")
print(f"最大值 max(): {data.max()}")
print(f"最小值 min(): {data.min()}")
print(f"标准差 std(): {data.std():.4f}")
print(f"方差 var(): {data.var():.4f}\n")

# 按维度聚合
print("按维度聚合：")
print(f"按行求和 sum(dim=1): {data.sum(dim=1)}")
print(f"按列求和 sum(dim=0): {data.sum(dim=0)}")
print(f"按行求平均 mean(dim=1): {data.mean(dim=1)}")

# 保持维度
print(f"\n保持维度 sum(dim=1, keepdim=True):\n{data.sum(dim=1, keepdim=True)}")

### 5.2 数学函数

In [ ]:
print("🔬 数学函数：")

# 创建测试数据
x = torch.linspace(-2, 2, 5)
print(f"输入 x: {x}\n")

# 激活函数
print("🧠 激活函数：")
print(f"ReLU: {torch.relu(x)}")
print(f"Sigmoid: {torch.sigmoid(x)}")
print(f"Tanh: {torch.tanh(x)}\n")

# 三角函数
print("📐 三角函数：")
print(f"Sin: {torch.sin(x)}")
print(f"Cos: {torch.cos(x)}\n")

# 指数和对数
positive_x = torch.abs(x) + 0.1  # 确保为正数
print("📈 指数和对数：")
print(f"指数 exp: {torch.exp(x)}")
print(f"对数 log: {torch.log(positive_x)}")
print(f"开方 sqrt: {torch.sqrt(positive_x)}")

---

## 🎯 6. 索引和切片

张量的索引和切片操作类似于NumPy，但有一些PyTorch特有的功能：

In [ ]:
print("🎯 索引和切片操作：")

# 创建一个3维张量
tensor_3d = torch.arange(24).reshape(2, 3, 4)
print(f"原始3D张量:\n{tensor_3d}\n")

print("🔍 基本索引：")
print(f"第0个元素 [0]: \n{tensor_3d[0]}\n")
print(f"第0行第1列 [0, 1]: {tensor_3d[0, 1]}\n")
print(f"特定元素 [0, 1, 2]: {tensor_3d[0, 1, 2]}\n")

print("✂️ 切片操作：")
print(f"前两行 [:2]: \n{tensor_3d[:2]}\n")
print(f"所有行的第1列 [:, 1]: \n{tensor_3d[:, 1]}\n")
print(f"最后两列 [:, :, -2:]: \n{tensor_3d[:, :, -2:]}\n")

print("🎲 高级索引：")
# 布尔索引
mask = tensor_3d > 10
masked_values = tensor_3d[mask]
print(f"大于10的元素: {masked_values}\n")

# 花式索引
indices = torch.tensor([0, 1, 0])
selected = tensor_3d[indices]
print(f"选择特定索引 [0, 1, 0]: \n{selected}")

---

## 🔗 7. 张量的拼接和分割

在深度学习中，经常需要组合或分割张量：

In [ ]:
print("🔗 张量拼接和分割：")

# 创建两个张量
t1 = torch.randn(2, 3)
t2 = torch.randn(2, 3)
print(f"张量1:\n{t1}")
print(f"张量2:\n{t2}\n")

print("🔗 拼接操作：")
# 按行拼接 (dim=0)
cat_dim0 = torch.cat([t1, t2], dim=0)
print(f"按行拼接 cat(dim=0):\n{cat_dim0}\n")

# 按列拼接 (dim=1)
cat_dim1 = torch.cat([t1, t2], dim=1)
print(f"按列拼接 cat(dim=1):\n{cat_dim1}\n")

# 堆叠 - 创建新维度
stacked = torch.stack([t1, t2], dim=0)
print(f"堆叠 stack(dim=0) 形状: {stacked.shape}")
print(f"堆叠结果:\n{stacked}\n")

print("✂️ 分割操作：")
# 等分分割
chunks = torch.chunk(cat_dim0, 2, dim=0)
print(f"等分为2块: {len(chunks)}个张量")
print(f"第一块:\n{chunks[0]}\n")

# 按指定大小分割
splits = torch.split(cat_dim1, 3, dim=1)
print(f"按大小3分割: {len(splits)}个张量")
print(f"第一块形状: {splits[0].shape}")

---

## 🔄 8. 张量与NumPy的互转

PyTorch张量可以与NumPy数组无缝转换：

In [ ]:
print("🔄 PyTorch与NumPy互转：")

# PyTorch → NumPy
pytorch_tensor = torch.randn(2, 3)
numpy_array = pytorch_tensor.numpy()  # 注意：共享内存！

print(f"PyTorch张量:\n{pytorch_tensor}")
print(f"转换为NumPy:\n{numpy_array}")
print(f"NumPy类型: {type(numpy_array)}\n")

# NumPy → PyTorch
numpy_data = np.array([[1, 2, 3], [4, 5, 6]])
torch_from_numpy = torch.from_numpy(numpy_data)  # 共享内存
torch_tensor = torch.tensor(numpy_data)  # 复制数据

print(f"NumPy数组:\n{numpy_data}")
print(f"from_numpy():\n{torch_from_numpy}")
print(f"tensor():\n{torch_tensor}\n")

# ⚠️ 注意：内存共享的影响
print("⚠️ 内存共享示例：")
pytorch_tensor[0, 0] = 999
print(f"修改PyTorch张量后的NumPy数组:\n{numpy_array}")
print("👆 注意：NumPy数组也被修改了！(共享内存)")

# 如果张量在GPU上，需要先移到CPU
if torch.cuda.is_available():
    gpu_tensor = torch.randn(2, 2).cuda()
    cpu_numpy = gpu_tensor.cpu().numpy()
    print(f"\nGPU张量转NumPy: {cpu_numpy.shape}")

---

## 💻 9. 设备操作 (CPU/GPU)

PyTorch可以在不同设备上运行，主要是CPU和GPU：

In [ ]:
print("💻 设备操作：")

# 检查CUDA可用性
print(f"CUDA可用: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA设备数量: {torch.cuda.device_count()}")
    print(f"当前CUDA设备: {torch.cuda.current_device()}")
    print(f"设备名称: {torch.cuda.get_device_name()}")

print(f"\n使用设备: {device}\n")

# 创建张量到指定设备
cpu_tensor = torch.randn(2, 3)  # 默认在CPU
print(f"CPU张量设备: {cpu_tensor.device}")

# 移动到GPU (如果可用)
gpu_tensor = cpu_tensor.to(device)
print(f"GPU张量设备: {gpu_tensor.device}")

# 直接在GPU创建张量
if torch.cuda.is_available():
    direct_gpu = torch.randn(2, 3, device='cuda')
    print(f"直接GPU张量设备: {direct_gpu.device}")

# 设备间运算规则
print("\n⚠️ 重要：只有相同设备的张量才能运算！")
try:
    # 这会出错（如果有GPU的话）
    if torch.cuda.is_available():
        result = cpu_tensor + direct_gpu  # 不同设备张量相加
except RuntimeError as e:
    print(f"错误: {e}")

# 正确做法：确保张量在同一设备
result = cpu_tensor.to(device) + gpu_tensor
print(f"\n正确运算结果设备: {result.device}")

# 内存使用情况 (GPU)
if torch.cuda.is_available():
    print(f"\nGPU内存使用:")
    print(f"已分配: {torch.cuda.memory_allocated() / 1e6:.1f} MB")
    print(f"已缓存: {torch.cuda.memory_reserved() / 1e6:.1f} MB")

---

## 🎯 10. 实战练习：图像数据处理

让我们用张量操作来处理一个实际的图像数据示例：

In [ ]:
print("🖼️ 实战：图像数据处理")

# 模拟一批RGB图像数据
# 形状: (批次大小, 通道数, 高度, 宽度)
batch_size, channels, height, width = 4, 3, 32, 32
images = torch.randn(batch_size, channels, height, width)

print(f"📊 图像批次信息:")
print(f"形状: {images.shape}")
print(f"数据类型: {images.dtype}")
print(f"数值范围: [{images.min():.3f}, {images.max():.3f}]\n")

# 1. 数据标准化 (常见预处理)
normalized = (images - images.mean()) / images.std()
print(f"📈 标准化后:")
print(f"均值: {normalized.mean():.6f}")
print(f"标准差: {normalized.std():.6f}\n")

# 2. 通道重排序 (BGR → RGB)
# 假设原始是BGR，转换为RGB
rgb_images = images[:, [2, 1, 0], :, :]  # 交换通道顺序
print(f"🎨 通道重排序后形状: {rgb_images.shape}\n")

# 3. 图像缩放 (双线性插值)
import torch.nn.functional as F
resized = F.interpolate(images, size=(64, 64), mode='bilinear', align_corners=False)
print(f"🔍 缩放后形状: {resized.shape}\n")

# 4. 数据增强：随机翻转
def random_flip(images, p=0.5):
    """随机水平翻转图像"""
    mask = torch.rand(images.size(0)) < p
    flipped = images.clone()
    flipped[mask] = torch.flip(flipped[mask], dims=[3])  # 沿宽度维度翻转
    return flipped

augmented = random_flip(images)
print(f"🎲 数据增强后形状: {augmented.shape}\n")

# 5. 批次统计
print(f"📊 批次统计:")
print(f"每个图像的均值: {images.mean(dim=[1,2,3])}")
print(f"每个通道的均值: {images.mean(dim=[0,2,3])}")
print(f"空间维度的均值: {images.mean(dim=[2,3]).shape}")

# 6. 展平用于全连接层
flattened_for_fc = images.view(batch_size, -1)
print(f"\n🔗 展平用于全连接层: {flattened_for_fc.shape}")
print(f"每个样本特征数: {flattened_for_fc.size(1)}")

---

## 📝 总结与关键要点

### 🎯 核心概念
1. **张量是PyTorch的基础数据结构**，类似于NumPy数组但支持GPU计算
2. **形状操作是关键技能**：reshape, view, transpose, permute等
3. **设备管理很重要**：确保张量在正确的设备上进行运算
4. **广播机制**让不同形状的张量可以进行运算

### 💡 实用技巧
- 使用 `print_tensor_info()` 函数检查张量属性
- 合理选择数据类型以节省内存
- 注意内存共享：`numpy()` vs `tensor()`
- GPU张量需要移到CPU才能转换为NumPy

### 🚀 下一步学习
- 自动求导机制 (Autograd)
- 神经网络构建 (nn.Module)
- 损失函数和优化器
- 数据加载和预处理

---

## 🏆 练习任务

完成以下练习来巩固张量操作：

In [ ]:
print("🏆 练习任务：")

# 练习1: 创建一个3x4的随机矩阵，然后:
# - 计算每行的和
# - 找出最大值及其位置
# - 转置矩阵
print("📝 练习1: 矩阵操作")
matrix = torch.randn(3, 4)
print(f"原矩阵:\n{matrix}")

# 你的代码在这里...
row_sums = matrix.sum(dim=1)
max_val, max_idx = matrix.max(), matrix.argmax()
transposed = matrix.T

print(f"每行和: {row_sums}")
print(f"最大值: {max_val}, 位置: {max_idx}")
print(f"转置后形状: {transposed.shape}\n")

# 练习2: 创建两个2x3矩阵，进行元素级乘法和矩阵乘法
print("📝 练习2: 矩阵运算")
A = torch.randn(2, 3)
B = torch.randn(3, 2)  # 注意形状以便矩阵乘法

# 你的代码在这里...
print(f"A形状: {A.shape}, B形状: {B.shape}")
print(f"矩阵乘法 A@B 形状: {(A @ B).shape}")

print("\n🎉 恭喜完成张量基础学习！")